// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBOSL5Aq8JI6NqRZWQJtqeCbZI9WSc8PPg',
    appId: '1:349349449804:web:1df405ed32218f938724e9',
    messagingSenderId: '349349449804',
    projectId: 'tiktokclone-77a41',
    authDomain: 'tiktokclone-77a41.firebaseapp.com',
    storageBucket: 'tiktokclone-77a41.appspot.com',
    measurementId: 'G-8FMM01LKBR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBGCENFxthV-7DCDTPzX1fNtG95f2hbHLE',
    appId: '1:349349449804:android:4dfc060dcbd15cbc8724e9',
    messagingSenderId: '349349449804',
    projectId: 'tiktokclone-77a41',
    storageBucket: 'tiktokclone-77a41.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDuO0Gluy5-kpFtouHVXQmq8ttC5vcUCsk',
    appId: '1:349349449804:ios:f4624019cf30fcc48724e9',
    messagingSenderId: '349349449804',
    projectId: 'tiktokclone-77a41',
    storageBucket: 'tiktokclone-77a41.appspot.com',
    iosBundleId: 'com.example.tiktokClone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDuO0Gluy5-kpFtouHVXQmq8ttC5vcUCsk',
    appId: '1:349349449804:ios:f4624019cf30fcc48724e9',
    messagingSenderId: '349349449804',
    projectId: 'tiktokclone-77a41',
    storageBucket: 'tiktokclone-77a41.appspot.com',
    iosBundleId: 'com.example.tiktokClone',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBOSL5Aq8JI6NqRZWQJtqeCbZI9WSc8PPg',
    appId: '1:349349449804:web:f509368583225d518724e9',
    messagingSenderId: '349349449804',
    projectId: 'tiktokclone-77a41',
    authDomain: 'tiktokclone-77a41.firebaseapp.com',
    storageBucket: 'tiktokclone-77a41.appspot.com',
    measurementId: 'G-YP2Q082EGQ',
  );
}
